import type { FunctionComponent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  fetchSystemLogFile,
  fetchSystemLogs,
  type SystemLogEntry,
  type SystemLogFileResponse,
  type SystemLogListResponse
} from "../api";
import { useComponentIdentity } from "../components/dashboard/primitives/useComponentIdentity";
import sharedStyles from "../styles/shared.module.css";
import styles from "./SystemLogsPage.module.css";
import { clientLogger } from "../utils/logging/clientLogger";

const formatTimestamp = (value: string): string => {
  const timestamp = Date.parse(value);
  if (Number.isNaN(timestamp)) {
    return value;
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
    timeZone: "UTC"
  }).format(timestamp);
};

export const SystemLogsPage: FunctionComponent = () => {
  const [data, setData] = useState<SystemLogListResponse | null>(null);
  const [selectedLog, setSelectedLog] = useState<SystemLogFileResponse | null>(null);
  const [selectedLogId, setSelectedLogId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isFileLoading, setIsFileLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { componentId, componentUid } = useComponentIdentity("system-logs-page");

  const loadLogs = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setError(null);
    try {
      const payload = await fetchSystemLogs();
      setData(payload);

      if (!payload.logs.some((log) => log.id === selectedLogId)) {
        setSelectedLog(null);
        setSelectedLogId(null);
      }
    } catch (loadError) {
      clientLogger.error("System logs list failed to load", { error: loadError });
      setError("Unable to load system logs right now.");
    } finally {
      setIsLoading(false);
    }
  }, [selectedLogId]);

  useEffect(() => {
    void loadLogs();
    const onGlobalRefresh = (): void => {
      void loadLogs();
    };
    window.addEventListener("global-data-refresh-requested", onGlobalRefresh);

    return () => {
      window.removeEventListener("global-data-refresh-requested", onGlobalRefresh);
    };
  }, [loadLogs]);

  const onLogSelect = async (entry: SystemLogEntry): Promise<void> => {
    setIsFileLoading(true);
    setSelectedLogId(entry.id);
    try {
      const payload = await fetchSystemLogFile(entry.id);
      setSelectedLog(payload);
    } catch (loadError) {
      clientLogger.error("System log file failed to load", { error: loadError, entryId: entry.id });
      setSelectedLog(null);
      setError("Unable to load selected system log file.");
    } finally {
      setIsFileLoading(false);
    }
  };

  const selectedLabel = useMemo(() => {
    if (!selectedLog) {
      return "No log file selected.";
    }

    return `${selectedLog.entry.category} • ${selectedLog.entry.fileName}`;
  }, [selectedLog]);

  return (
    <section className={sharedStyles["timeline-page"]} data-component-id={componentId} data-component-uid={componentUid}>
      <header className={sharedStyles["timeline-header"]}>
        <p className={sharedStyles["timeline-kicker"]}>Observability</p>
        <h2>System Logs</h2>
        <p className={sharedStyles["timeline-subtitle"]}>
          Prompt submission/request/response files plus ingestion event records generated by backend data refresh workflows.
        </p>
      </header>

      <section className={sharedStyles["timeline-controls"]}>
        <button
          type="button"
          className={sharedStyles["timeline-control-button"]}
          onClick={() => {
            void loadLogs();
          }}
          disabled={isLoading}
        >
          Refresh
        </button>
      </section>

      {error ? <p className={sharedStyles["timeline-error"]}>{error}</p> : null}

      <section className={styles["system-logs-layout"]}>
        <article className={sharedStyles.panel}>
          <h3>Files ({data?.logs.length ?? 0})</h3>
          {isLoading ? <p className={sharedStyles.subtle}>Loading files…</p> : null}
          {!isLoading && (data?.logs.length ?? 0) === 0 ? <p className={sharedStyles.subtle}>No log files found yet.</p> : null}
          <ul className={styles["system-logs-list"]}>
            {(data?.logs ?? []).map((entry) => (
              <li key={entry.id}>
                <button
                  type="button"
                  className={`${styles["system-logs-item"]} ${selectedLogId === entry.id ? styles["system-logs-item-selected"] : ""}`}
                  onClick={() => {
                    void onLogSelect(entry);
                  }}
                >
                  <span>{entry.category}</span>
                  <strong>{entry.fileName}</strong>
                  <small>{formatTimestamp(entry.modifiedAt)} UTC</small>
                </button>
              </li>
            ))}
          </ul>
        </article>

        <article className={sharedStyles.panel}>
          <h3>{selectedLabel}</h3>
          <textarea
            readOnly
            value={isFileLoading ? "Loading file…" : selectedLog?.content ?? "Select a file from the left panel."}
            className={styles["system-logs-textbox"]}
          />
        </article>
      </section>
    </section>
  );
};
